### ISSUE TITLE
Is checkout step really necessary? 

### ISSUE THREAD

**Issue by Ameausoone** [harupy/comment-on-pr#21]
In your example: 

```
    steps:
      - uses: actions/checkout@master
      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: template.md
```

Does the step `actions/checkout@master` is really necessary for add a comment on a PR ? 

Pipeline would be slightly faster without checkout step.
